import { Pos } from 'esast/lib/Loc';
import Char from 'typescript-char/Char';
export declare let index: number;
export declare let line: number;
export declare let column: number;
export declare let sourceString: string;
export declare function setupSourceContext(source: string): void;
export declare function pos(): Pos;
export declare function peek(n?: number): Char;
export declare function eat(): Char;
export declare function skip(n?: number): void;
export declare function tryEat(charToEat: Char): boolean;
export declare function tryEatIf(pred: (_: Char) => boolean): boolean;
export declare function tryEat2(char1: Char, char2: Char): boolean;
export declare function tryEatNewline(): boolean;
export declare function stepBackMany(oldPos: Pos, nCharsToBackUp: number): void;
export declare function skipRestOfLine(): void;
export declare function takeRestOfLine(): string;
export declare function takeName(): string;
export declare function isNameCharacter(ch: Char): boolean;
export declare function isAllNameCharacters(str: string): boolean;
export declare function skipSpaces(): number;
export declare function skipTabs(): number;
export declare function skipNumBinary(): void;
export declare function skipNumOctal(): void;
export declare function skipNumHex(): void;
export declare function skipNumDecimal(): void;
export declare function isDigitDecimal(_: Char): boolean;
export declare function skipNewlines(): number;
